### PR TITLE
Bump css-to-react-native-transform to 2.0

### PR DESCRIPTION
**Pull request by marlonmarcello**
@kristerkari I hope this is okay!

I am currently having a parse issue:
`Failed to parse declaration "flex: 1 1 0%"`

Which I have a feeling got fixed by this https://github.com/styled-components/css-to-react-native/pull/44 and we just have to bring the updates upstream.

Might have to bump css-to-react-native-transform too jus to be sure https://github.com/kristerkari/css-to-react-native-transform/pull/129

### CODE REVIEW

**Comment by marlonmarcello** [comment]
My bad I think the problem still persists in `css-to-react-native` https://github.com/styled-components/css-to-react-native/issues/180

**Comment by kristerkari** [comment]
@marlonmarcello no problem :)

**Comment by marlonmarcello** [comment]
@kristerkari after digging a little more I managed to isolate the problem and it's indeed the use of an older version of that package. Version `1.8` is missing this line https://github.com/styled-components/css-to-react-native/blob/master/src/transforms/flex.js#L46 which breaks parsing of flex declarations with percentage

**Comment by kristerkari** [comment]
@marlonmarcello alright, well, I'll just update dep and release a new version.

**Comment by marlonmarcello** [comment]
Thanks @kristerkari ! Feel free to close this then when you are done.

**Comment by kristerkari** [comment]
@marlonmarcello I released a new version: https://github.com/kristerkari/react-native-postcss-transformer/releases/tag/1.3.0

Please try it out and see if it fixes the problem :)

**Comment by marlonmarcello** [comment]
Getting an error now `Failed to construct transformer:  TypeError: semver is not a function`. [Opened a PR](https://github.com/kristerkari/react-native-postcss-transformer/pull/31) with a fix for it.

**Pull request merged**
